### ISSUE TITLE
ValueError: Only call `sparse_softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

### ISSUE THREAD

**Issue by Strider20151** [KGPML/Hyperspectral#8]
Hi, thanks for your code. When I run the "CNN_feed"or "MLP_feed", I meet this error, and I cannot fix it. Do you know the solution?Can you help me? Thanks very much. My platform is Ubuntu 16.04, Anaconda2(python2.7), tensorflow1.0.1.

**Comment by Lane565** [comment]
Did you solve the problem? is it caused by version of tensorflow ?
